### ISSUE TITLE
Rule order not saved, SMTP header address selection not saved

### ISSUE THREAD

**Issue by troogyt** [networkException/thundersort#57]
Thundersort v1.1.0.

It's nearly doing what I need, but it seems to have a couple of minor bugs still.

1. When I change the rule order, it is not saved.
2. The displayed order of the rules seems to be inconsistent. They are sometimes reversed when opening the settings page.
3. When I change the field selection for each rule from `recipient` to `sender` it is not saved.

This might be a permissions thing preventing the config from being saved, but I am not sure where to look for that.

What I want:
![image](https://github.com/networkException/thundersort/assets/41710820/e305e3ed-ee9a-43b1-964a-2ea5efc3cc52)

What I keep getting:
![image](https://github.com/networkException/thundersort/assets/41710820/7ba7993e-de66-48dd-9b06-4d4b672c8a03)

**Comment by troogyt** [comment]
I ran grep on one string from the above in the Thunderbird profile directory and found the rules are stored as a JSON text string in  the SQLite database file `"C:\Users\USERNAME\AppData\Roaming\Thunderbird\Profiles\PROFILE\storage-sync-v2.sqlite"`.

The JSON db record appears partially correct (i.e. what I tried to configure):
_Note: I copied the field text into Notepad++ and ran JSON Pretty Print - the db record is one line_
![image](https://github.com/networkException/thundersort/assets/41710820/b3d996dd-37f6-4e5e-9765-092aeafae826)

This has me wondering two things:
1. when/how does this record get re-read into (i.e. re-applied to) the live running Thunderbird instance/config?
2. is there a case for explicitly adding a Rule Sequence field where the user can easily reorder the rules by updating the sequence numbers for each rule?

_Note: my rules above are currently mutually exclusive, but it is entirely possible to have multiple rules that would match a single message, so controlling the sequence by explicit sequence numbers rather than by having to rewrite all the rules in order would be great_

**Comment by networkException** [comment]
> When I change the rule order, it is not saved.

I'm not exactly sure what you mean?

> The displayed order of the rules seems to be inconsistent. They are sometimes reversed when opening the settings page.

I made a dumb mistake there, fixed in b981fad1025a219a31e20c716a43b177081ef627

> When I change the field selection for each rule from `recipient` to `sender` it is not saved.

Oops yes, fixed in 112f4225e3460394e0d4459841194bc28c0fc5f2

> is there a case for explicitly adding a Rule Sequence field where the user can easily reorder the rules by updating the sequence numbers for each rule?

I added a move up / down button for this in 244bf60e4b63fc8c7a89d465e85337c920c4d1a8, I hope that works for you

**Comment by troogyt** [comment]
I am so sorry...I can't get it to compile now. `npm run bundle` fails.
```
$npm run bundle

> bundle
> ./bundle.sh

/usr/bin/env: ‘bash\r’: No such file or directory
```
So then I tried changing the shebang from `#!/usr/bin/env bash` to `#!/usr/bin bash` because that's where bash is, but then I got:
```
$npm run bundle

> bundle
> ./bundle.sh

sh: 1: ./bundle.sh: Permission denied
```
So then I thought running `./bundle.sh` on it's own might work, but I got:
```
$./bundle.sh
bash: ./bundle.sh: /usr/bin: bad interpreter: Permission denied
```
If I try `bash bundle.sh` I get:
```
$bash bundle.sh
bundle.sh: line 2: $'\r': command not found
rm: cannot remove 'dist'$'\r': No such file or directory


                This is not the tsc command you are looking for


To get access to the TypeScript compiler, tsc, from the command line either:

- Use npm install typescript to first add TypeScript to your project before using npx
- Use yarn to avoid accidentally running code from un-installed packages
cp: target 'dist/'$'\r' is not a directory
rm: cannot remove 'thundersort.xpi'$'\r': No such file or directory
```
I am wondering if you could include the zip file on here?
Or is it system dependent when compiled?

**Comment by networkException** [comment]
Did you open the file in an editor under Windows? There shouldn't be a \r at the line ending. (Windows uses \r\n as line endings for historical reasons, Linux expects \n, as such an editor auto replacing \n with \r\n could have caused the error you're seeing)

**Comment by troogyt** [comment]
ahh...well, Notepad++. It may have added that. Silly me...that skeleton keeps finding new closets :P

I have edited `bundle.sh` so
![image](https://github.com/networkException/thundersort/assets/41710820/e416e1f1-3077-4ef9-b8c1-aa4f20085909)

is now
![image](https://github.com/networkException/thundersort/assets/41710820/ad6b5d64-4f8a-4724-886d-b4deeb2d3d8a)

And so now it works:
![image](https://github.com/networkException/thundersort/assets/41710820/3b1cbc03-9130-478c-b3b1-57eb8e975bf2)

Many thanks again, and sleep well! I think you sleep when I wake (in Sydney).

**Comment by troogyt** [comment]
I think I spoke too soon...it seems it did not create the `dist/` directory, and when I tried to re-run it, it hit a new permissions issue:
![image](https://github.com/networkException/thundersort/assets/41710820/533d8ac6-ecb9-4f3a-9abc-5dfcb05b5ad5)

I changed `bundle.sh` to:
![image](https://github.com/networkException/thundersort/assets/41710820/5b8dadf7-f1c1-48f7-86cb-fb7f18a30a3d)
This appears to have fixed the `cp: target 'dist/' is not a directory` issue and now it is creating `dist/` and generating `thundersort.xip` with the `dist/` directory as expected.

A little research indicates to me that `cp` cannot or does not automatically create the top level directory if it does not already exist....but it's a little confusing since yesterday's compilation worked (v1.1.0)...strange. Anyway...

**Comment by troogyt** [comment]
And now I can load the addon from the `xpi` file, but I can't edit the Rules :-/
![image](https://github.com/networkException/thundersort/assets/41710820/1a83883b-6211-4d20-8224-1c75bc45f3e3)

Running Beyond Compare between 1.1.0 and 1.2.0 folders has revealed that all other text files in 1.2.0 appear to have been '_CRLF'd_' :-/
I think this might be github desktop on Windows, and I also suspect this may be the reason the `src/types/` directory was not copied into the `dist/`...
I will check the repo here but to be safe I might do `Find/Replace in Files` in Notepad++ to get rid of every instance of `CR` in every file...

**Comment by troogyt** [comment]
![image](https://github.com/networkException/thundersort/assets/41710820/63c7f224-d62e-4cd6-b390-013d485a8e87)

Still, recompiling after this, `src/types/` is not included and none of the `*.js`, `*.ts` or `*.map` files included, so it appears `npx tsc -p tsconfig.json` in `bundle.sh` is basically not being executed.

Taking this hint
![image](https://github.com/networkException/thundersort/assets/41710820/4d1159ab-080d-4deb-8898-064b00950f2c)

I ran `npm install`. It didn't realize I had to run this for each version....
![image](https://github.com/networkException/thundersort/assets/41710820/c5bf1a74-2648-493e-826c-391b688ee896)
Looks like it is compiling now...

**Comment by troogyt** [comment]
However, I noticed I have to 'load it twice' into TB...it's weird. The first time I load it from the `xpi` file, the little spanner icon is usually missing:
![image](https://github.com/networkException/thundersort/assets/41710820/fd91ecb4-745c-4286-aa1f-2da48b102285)
So I have to load it a second time.

--- Anyway ---

Now it is loaded, I have found that doing this only partially works:
![image](https://github.com/networkException/thundersort/assets/41710820/72b60153-5cd9-4975-9660-c350e93cbd70)

It seems to process all emails when I actually `CTRL+A` select them all in the actually message list pane then right click and run it on messages.

But... IT WORKS!!! Yay! :D

**Comment by troogyt** [comment]
I hope all the above posts are of benefit to other people...

**Comment by troogyt** [comment]
I think it may be deleting messages instead of moving them 8-(
I created a separate profile for this (and am using a not so important account), so hopefully I can import a backup `msf` file...

**Comment by troogyt** [comment]
Ok, I do not think it deleted any messages (phew!). I think this was the issue:
![image](https://github.com/networkException/thundersort/assets/41710820/e81db390-7bf9-4249-98ec-9896760f2b93)

However, it does seem like it does not necessarily process all emails in the whole folder. It created all the new `tld.domain@user` folders, but did not seem to finish moving all the messages. I don't know if that was due to IMAP synchronisation interferring or something else.

I am selecting groups of emails directly in the message list window, and using the right click context menu to move them. This appears to be working. Once I have moved everything manually I will do some automatic message filing tests with new emails and see if it does catch the new inbound messages and file them accordingly.

Also, it doesn't seem to work on Local Folders. This is not as important, I guess, but is this limited to IMAP/POP3 folders only?

**Comment by troogyt** [comment]
I have just done a lot of testing. It is almost working fully. I noticed a couple of messages were sorted on the `Reply-To` field rather than the original `Sender` field. Is this by design?

Also, sometimes the rate at which it seems to be processing messages is significantly slower. It is usually pretty zippy.
Plus, I sometimes have to `Repair Folder` again because after processing some messages they have disappeared from the source folder but not appeared in the destination folder. `Repairing` usually fixes this, but not sure why this happens. Smells like a possible race condition, maybe?

But....having said all of the above, I want to thank you for this add-on. It is truly the first and only add-on I have found that is able to file messages based on the SMTP Sender using regular expressions for matching...long search is over :)

**Comment by networkException** [comment]
However, I noticed I have to 'load it twice' into TB...it's weird. The first time I load it from the xpi file, the little spanner icon is usually missing

> Yea thunderbird is weird like that, super annoying when debugging

**Comment by networkException** [comment]
> Also, it doesn't seem to work on Local Folders. This is not as important, I guess, but is this limited to IMAP/POP3 folders only?

hm I'm not sure, perhaps their api doesn't cover everything...

Also I'm aware of at least some janky-ness when sorting a folder, for me it usually kills the sorting process after a few hundred mails and I have to click sort again.

For everything else you probably have to debug yourself, it might be platform related sadly :/

**Comment by troogyt** [comment]
One final question: if I place a forward slash or backslash in the replacement string, does it create a subfolder?

Defo 'janky'. `java` = `janky` from my POV :P

**Comment by networkException** [comment]
Nope thats not implemented currently, see #2

Shouldn't be hard to add tho

**Comment by troogyt** [comment]
That would be stupendous because it would enable drilling down into the domain with the most unread messages more rapidly. Some domains have a lot more users (e.g. gmail.com) than others.

**Comment by networkException** [comment]
> I noticed a couple of messages were sorted on the Reply-To field rather than the original Sender field. Is this by design?

Not really design but my assuptions about how people would use the feature. I guess it dosen't make sense?

**Comment by troogyt** [comment]
I notice there seems to be a length limit to the resultant `slug`/`folder`. TB limit?

**Comment by troogyt** [comment]
How about that. Forward slashes produced this:
![image](https://github.com/networkException/thundersort/assets/41710820/afe02a49-cafe-418b-8d17-1d11cd9973f2)
